### ISSUE TITLE
password for admin

### ISSUE THREAD

**Issue by monalisa62003** [Bazhful/loginphp#1]
hi i cant figure out the password for admin?

**Comment by Bazhful** [comment]
There is no password:)

tis 22 dec. 2020 kl. 00:59 skrev monalisa62003 <notifications@github.com>:

**Comment by chroakPRO** [comment]
try no password and remove the appenv require🙂 i can't say for sure since I don't know your db password.  But default phpmyadmin is no password

**Comment by monalisa62003** [comment]
what i mean is to login to the actual app. i c&p the stuff from the login text file but it didnt log in

**Comment by chroakPRO** [comment]
Hello there just updated it and fixed it sort of, it was the htmlspecialchars that caused trouble. Just redownload the repo and load the new database called apps.sql and everything will work check the new user and password. Also keep in mind that the password is not currently cleaned or have any sort of sql injektion cleaning except prepared statements. Hope that helps, I would recommend adding some sort of regex cleaning for the strings or something like that atleast. I have another that repo that deals with string validation, that can be used in a if command it check if its true not.
